[package]
name = "plexus"
version = "0.0.5"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/olson-sean-k/plexus"
description = "3D mesh generation and manipulation."
keywords = ["graphics", "half-edge", "mesh", "topology"]

[package.metadata.docs.rs]
# Enable all featues so that trait implementations for types from commonly used
# linear algebra crates are shown.
all-features = true
rustdoc-args = ["--no-defaults",
                "--passes=collapse-docs",
                "--passes=strip-hidden",
                # Omitting this pass exposes documentation for aliased and
                # dereferenced types, as well as types that are not
                # re-exported. When this is used, the documentation is
                # incomplete. However, it also generates a lot of spurious
                # documentation.
                #
                # https://github.com/rust-lang/rust/issues/39437
                "--passes=strip-private",
                "--passes=strip-priv-imports",
                "--passes=unindent-comments"]

[badges]
travis-ci = { repository = "olson-sean-k/plexus" }

[lib]
name = "plexus"

[features]
default = ["geometry-nalgebra"]
geometry-cgmath = ["cgmath"]
geometry-nalgebra = ["alga", "nalgebra"]

[dependencies]
arrayvec = "0.3.*"
derivative = "1.0.*"
itertools = "0.6.*"
num = "0.1.*"
ordered-float = "0.5.*"

alga = { version = "0.5.*", optional = true }
cgmath = { version = "0.15.*", optional = true }
nalgebra = { version = "0.13.*", optional = true }
