[package]
name = "plexus"
version = "0.0.0"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/olson-sean-k/plexus"
description = "3D mesh generation and manipulation."
keywords = ["mesh", "graphics"]

[badges]
travis-ci = { repository = "olson-sean-k/plexus" }

[lib]
name = "plexus"

[dependencies]
arrayvec = "0.3.*"
itertools = "0.6.*"
num = "0.1.*"

[dev-dependencies]
ordered-float = "0.5.*"
