[package]
name = "plexus"
version = "0.0.3"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/olson-sean-k/plexus"
description = "3D mesh generation and manipulation."
keywords = ["mesh", "graphics"]

[package.metadata.docs.rs]
# Enable all featues so that trait implementations for types from commonly used
# linear algebra crates are shown.
all-features = true
# Omit the `strip-private` pass to expose documentation for aliased and
# dereferenced types and types that are not re-exported.
#
# https://github.com/rust-lang/rust/issues/39437
rustdoc-args = ["--no-defaults",
                "--passes=collapse-docs",
                "--passes=strip-hidden",
                "--passes=strip-priv-imports",
                "--passes=unindent-comments"]

[badges]
travis-ci = { repository = "olson-sean-k/plexus" }

[lib]
name = "plexus"

[features]
default = ["geometry-nalgebra"]
geometry-cgmath = ["cgmath"]
geometry-nalgebra = ["alga", "nalgebra"]

[dependencies]
arrayvec = "0.3.*"
itertools = "0.6.*"
num = "0.1.*"
ordered-float = "0.5.*"

alga = { version = "0.5.*", optional = true }
cgmath = { version = "0.15.*", optional = true }
nalgebra = { version = "0.11.*", optional = true }

[dev-dependencies]
derivative = "1.0.*"
